FROM alpine
RUN apk update \
    && apk add nginx \
    && adduser -D -g 'www' www \
    && mkdir /www \
    && chown -R www:www /var/lib/nginx \
    && chown -R www:www /www 
COPY ./nginx.conf /etc/nginx/nginx.conf
VOLUME [ "/www" ]
VOLUME [ "/var/log/nginx" ]
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]